// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// chenyingyi11
Rcpp::List chenyingyi11(const arma::mat& X, const arma::colvec& y, double lambda);
RcppExport SEXP _homework222_chenyingyi11(SEXP XSEXP, SEXP ySEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(chenyingyi11(X, y, lambda));
    return rcpp_result_gen;
END_RCPP
}
// chenyingyi22
Rcpp::List chenyingyi22(const arma::mat& X, const arma::colvec& y, double lambda);
RcppExport SEXP _homework222_chenyingyi22(SEXP XSEXP, SEXP ySEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(chenyingyi22(X, y, lambda));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_homework222_chenyingyi11", (DL_FUNC) &_homework222_chenyingyi11, 3},
    {"_homework222_chenyingyi22", (DL_FUNC) &_homework222_chenyingyi22, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_homework222(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
